console.time("your code took")
console.log(3+3)
console.log("hello world")
console.log(true)
console.log([1 ,2 ,3, 4])
console.log({harry: "instructor" , age: "34"})
console.table({harry: "instructor" , age: "34"})
console.warn("this is a warning")
// console.clear()
console.timeEnd("your code took")